### ISSUE TITLE
Invalid secret config should display an helpful error message

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/helm-kubectl-boshrelease#4]
## expected behavior

as a developer, in order to debug incorrect secret syntax, I need an helpful error message.

## observed behavior

given the following secrets config,

```yaml
- type: replace
  path: /instance_groups/name=cfcr-helm-addons/jobs/name=helm/properties/secrets/-
  value:
    name: redis-ha-credhub-secret
    namespace: gberche-namespace
    data:
      - auth: ((redis-ha-password))
```

I don't see helpful error message.

Relates to https://github.com/orange-cloudfoundry/helm-kubectl-boshrelease/pull/3
